apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: croffle
  name: croffle
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: croffle
  template:
    metadata:
      labels:
        app: croffle
    spec:
      containers:
        - image: juu924/croffle:latest
          imagePullPolicy: Always
          name: croffle
          resources: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: croffle
  name: croffle
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: croffle
  type: LoadBalancer
